from transformers import GPT2Tokenizer, GPT2Model
import torch
from torch.nn.functional import cosine_similarity, normalize
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from hiq.vis import print_model
"""
🌳 GPT2Model<all params:124439808>
├── Embedding(wte)|weight[50257,768]
├── Embedding(wpe)|weight[1024,768]
├── ModuleList(h)
│   └── 💠 GPT2Block(0-11)<🦜:7087872x12>
│       ┣━━ 💠 LayerNorm(ln_1,ln_2)<🦜:1536x2>|weight[768]|bias[768]
│       ┣━━ GPT2Attention(attn)
│       ┃   ┣━━ Conv1D(c_attn)|weight[768,2304]|bias[2304]
│       ┃   ┗━━ Conv1D(c_proj)|weight[768,768]|bias[768]
│       ┗━━ GPT2MLP(mlp)
│           ┣━━ Conv1D(c_fc)|weight[768,3072]|bias[3072]
│           ┗━━ Conv1D(c_proj)|weight[3072,768]|bias[768]
└── LayerNorm(ln_f)|weight[768]|bias[768]
"""

# Load the tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
print_model(model)
# Function to get the embeddings from the embedding layer without special tokens
def get_embedding_layer_embedding(word):
    input_ids = tokenizer(word, return_tensors='pt', add_special_tokens=False)['input_ids']
    print(f"Tokenized input for '{word}': {input_ids}")
    with torch.no_grad():
        embedding_layer_output = model.get_input_embeddings()(input_ids)
    print(f"Embedding shape for '{word}': {embedding_layer_output.shape}")
    avg_embedding = embedding_layer_output.mean(dim=1)  # Average over the sequence length dimension
    return avg_embedding.squeeze()

# Function to get the embeddings from the final model output in a given context
def get_model_output_embedding(model, word, context_sentence):
    inputs = tokenizer(context_sentence, return_tensors='pt')
    word_tokens = tokenizer(word, add_special_tokens=False)['input_ids']
    print(f"Tokenized '{word}' in context '{context_sentence}': {word_tokens}")
    with torch.no_grad():
        outputs = model(**inputs)
    # Find the indices of the word tokens in the input_ids
    input_ids = inputs['input_ids'][0].tolist()
    print(f"Input IDs for context '{context_sentence}': {input_ids}")
    token_indices = []
    for i in range(len(input_ids) - len(word_tokens) + 1):
        if input_ids[i:i + len(word_tokens)] == word_tokens:
            token_indices.extend(range(i, i + len(word_tokens)))
            break
    if not token_indices:
        raise ValueError(f"Word '{word}' not found in the context: '{context_sentence}'")
    print(f"Token indices for '{word}': {token_indices}")
    # Extract the embeddings for the word tokens and average them
    final_layer_output = outputs.last_hidden_state[:, token_indices, :]
    avg_embedding = final_layer_output.mean(dim=1)
    return avg_embedding.squeeze()

# Words to analyze
words = [' king', ' queen', ' man', ' woman', ' apple', ' rope']

# Context sentences
contexts = {
    ' king': ["The king is wise.", "The king and queen rule the kingdom."],
    ' queen': ["The queen is kind.", "The queen is one of the great bands in history."],
    ' man': ["The man is strong.", "The man and woman are friends."],
    ' woman': ["The woman is smart.", "The woman and man are friends."],
    ' apple': ["The king eats apple every day.", "How much is an apple music account?"],
    ' rope': ["Hang the apple with a rope.", "positional embedding can be generated by rope algorithm."]
}

# Get static embeddings from the embedding layer
static_embeddings = {word: (get_embedding_layer_embedding(word).unsqueeze(0)).squeeze() for word in words}

# Get dynamic embeddings from the model output in different contexts
dynamic_embeddings = {}
for word in words:
    dynamic_embeddings[word] = []
    for context in contexts[word]:
        try:
            embedding = (get_model_output_embedding(model, word, context).unsqueeze(0)).squeeze()
            dynamic_embeddings[word].append(embedding)
        except ValueError as e:
            print(e)
            dynamic_embeddings[word].append(torch.zeros(model.config.n_embd))

# Prepare dynamic embeddings for the first and second context
dynamic_embeddings_first_context = {word: dynamic_embeddings[word][0] for word in words}
dynamic_embeddings_second_context = {word: dynamic_embeddings[word][1] for word in words}

def plot_word_pair_embedding(a, b, word1, word2):
    a = a.squeeze()
    b = b.squeeze()
    if a.shape != b.shape:
        raise ValueError("Vectors a and b must have the same dimensions for plotting.")
    # Create the plot
    plt.style.use('ggplot')
    plt.figure(figsize=(12, 6))  # Adjust the figure size as needed
    # Plot vector 'a'
    plt.plot(a.numpy(), label=word1, linestyle='-', marker='o', markersize=4, alpha=0.5)
    # Plot vector 'b'
    plt.plot(b.numpy(), label=word2, linestyle='--', marker='x', markersize=4, alpha=0.5)
    # Add labels and title
    plt.xlabel('Hidden Dimension', fontsize=10)
    plt.ylabel('Embedding Raw Value', fontsize=10)
    plt.title(f'Line Plot of Word Embeddings({word1} and {word2})', fontsize=10)
    plt.legend(fontsize=10)
    plt.grid(axis='y', alpha=0.5)  # Add a subtle grid
    # Show the plot
    plt.tight_layout()
    plt.show()

# Function to visualize cosine similarity
def visualize_cosine_similarity(ax, words, embeddings, embeddings_title, plot_ab=False):
    cos_sim_matrix = np.ones((len(words), len(words)))
    for i, word1 in enumerate(words):
        for j, word2 in enumerate(words):
            if i != j:
                a = embeddings[word1].unsqueeze(0)
                b = embeddings[word2].unsqueeze(0)
                if plot_ab and i==0:
                    plot_word_pair_embedding(a, b, word1, word2)
                sim = cosine_similarity(a, b).item()
                cos_sim_matrix[i, j] = sim
    sns.heatmap(cos_sim_matrix, xticklabels=words, yticklabels=words, annot=True, cmap='Reds', vmin=0, vmax=1, ax=ax, annot_kws={"size": 9})
    ax.set_title(f'Cosine Similarity between {embeddings_title} Word Embeddings', fontsize=8)

# Function to visualize distances
def visualize_distances(ax, words, embeddings, embeddings_title):
    dist_matrix = np.zeros((len(words), len(words)))
    for i, word1 in enumerate(words):
        for j, word2 in enumerate(words):
            if word1 != word2:
                d = torch.dist(embeddings[word1], embeddings[word2]).item()
                dist_matrix[i, j] = d
    sns.heatmap(dist_matrix, xticklabels=words, yticklabels=words, annot=True, cmap='Blues', vmin=0, ax=ax, annot_kws={"size": 9})
    ax.set_title(f'Distances between {embeddings_title} Word Embeddings', fontsize=8)

# Create subplots for cosine similarity
fig, axs = plt.subplots(1, 3, figsize=(14, 5))
visualize_cosine_similarity(axs[0], words, static_embeddings, "Static")
visualize_cosine_similarity(axs[1], words, dynamic_embeddings_first_context, "Dynamic (Context 1)", plot_ab=True)
visualize_cosine_similarity(axs[2], words, dynamic_embeddings_second_context, "Dynamic (Context 2)")
plt.suptitle("GPT2 Word Embedding Similarity", fontsize=10)
plt.tight_layout()
plt.savefig("gpt2_word_embedding_simi.png")
plt.show()

# Create subplots for distances
fig, axs = plt.subplots(1, 3, figsize=(14, 5))
visualize_distances(axs[0], words, static_embeddings, "Static")
visualize_distances(axs[1], words, dynamic_embeddings_first_context, "Dynamic (Context 1)")
visualize_distances(axs[2], words, dynamic_embeddings_second_context, "Dynamic (Context 2)")
plt.suptitle("GPT2 Word Embedding Distance", fontsize=10)
plt.tight_layout()
plt.savefig("gpt2_word_embedding_diff.png")
plt.show()
