import torch
import seaborn as sns
from torch.nn.functional import cosine_similarity
import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial.distance import cosine

plt.style.use('ggplot')

CONTEXTS = {
    'king': ["The king is wise.", "The king and queen rule the kingdom."],
    'queen': ["The queen is kind.", "The queen is one of the great bands in history."],
    'man': ["The man is strong.", "The man and woman are friends."],
    'woman': ["The woman is smart.", "The woman and man are friends."],
    'apple': ["The king eats apple every day.", "How much is an apple music account?"],
    #'rope': ["Hang the apple with a rope.", "positional embedding can be generated by rope algorithm."],
    'flies': ["fruit flies like an apple.", "time flies like an arrow.it's become sort of a colloquialism now. You don't really understand it until you reach your late 30s and early 40s - and I'm sure time will move even faster as I get older."]
}
WORDS = list(CONTEXTS.keys())


def words_for_bpe(ws):
    return [' ' + i for i in ws]


def contexts_for_bpe(ctx):
    r = {}
    for k, v in ctx.items():
        r[' ' + k] = v
    return r


def words_contexts_for_bpe(ws, ctx):
    return words_for_bpe(ws), contexts_for_bpe(ctx)


def get_embedding_layer_embedding(model, tokenizer, word):
    input_ids = tokenizer(word, return_tensors='pt', add_special_tokens=False)['input_ids']
    print(f"Tokenized input for '{word}': {input_ids}")
    with torch.no_grad():
        embedding_layer_output = model.get_input_embeddings()(input_ids)
    print(f"Embedding shape for '{word}': {embedding_layer_output.shape}")
    avg_embedding = embedding_layer_output.mean(dim=1)  # Average over the sequence length dimension
    return avg_embedding.squeeze()



def make_valid_filename(title: str) -> str:
    import re
    title = title.replace(" ", "_").replace("(", "_").replace(")", "_")
    title = re.sub(r'[^\w\.-]', '', title)
    title = re.sub(r'_+', '_', title)
    title = title.strip("_-.")
    return title


def plot_word_pair_embedding(a, b, word1, word2, embeddings_title, ax):
    a = a.squeeze()
    b = b.squeeze()
    if a.shape != b.shape:
        raise ValueError("Vectors a and b must have the same dimensions for plotting.")
    ax.plot(a.numpy(), label=word1, linestyle='-', marker='o', markersize=4, alpha=0.5)
    ax.plot(b.numpy(), label=word2, linestyle='--', marker='x', markersize=4, alpha=0.5)
    ax.set_xlabel('Hidden Dimension', fontsize=10)
    ax.set_ylabel('Embedding Raw Value', fontsize=10)
    ax.set_title(f'{embeddings_title} Word Embeddings({word1} vs {word2})', fontsize=10)
    ax.legend(fontsize=10)
    ax.grid(axis='y', alpha=0.5)


def line_plot_word_embedding(words, embeddings, embeddings_title, plot_ab=False):
    num_plots = len(words)-1  # Number of unique word pairs
    fig, axes = plt.subplots(num_plots, 1, figsize=(10, num_plots * 3))  # Adjust figure size as needed

    plot_index = 0
    for i, word1 in enumerate(words):
        for j, word2 in enumerate(words):
            if i != j:
                a = embeddings[word1].unsqueeze(0)
                b = embeddings[word2].unsqueeze(0)
                if plot_ab and i == 0:
                    plot_word_pair_embedding(a, b, word1, word2, embeddings_title, axes[plot_index])
                    plot_index += 1

    plt.tight_layout()
    plt.savefig(make_valid_filename(f"{embeddings_title.lower()}_word_embeddings"))
    plt.show()


def visualize_cosine_similarity(ax, words, embeddings, embeddings_title, ignore_outliner=False):
    cos_sim_matrix = np.ones((len(words), len(words)))
    for i, word1 in enumerate(words):
        for j, word2 in enumerate(words):
            if i != j:
                a = embeddings[word1].unsqueeze(0)
                b = embeddings[word2].unsqueeze(0)
                if ignore_outliner:
                    sim = cossim_wo_outliers(a, b)
                else:
                    sim = cosine_similarity(a, b).item()
                cos_sim_matrix[i, j] = sim
    sns.heatmap(cos_sim_matrix, xticklabels=words, yticklabels=words,
                annot=True,
                cmap='Reds',
                vmin=0,
                vmax=1,
                ax=ax,
                annot_kws={"size": 9})
    ax.set_title(f'Cosine Similarity between {embeddings_title} Word Embeddings', fontsize=8)


# Function to visualize distances
def visualize_distances(ax, words, embeddings, embeddings_title, ignore_outliner=False):
    dist_matrix = np.zeros((len(words), len(words)))
    for i, word1 in enumerate(words):
        for j, word2 in enumerate(words):
            if word1 != word2:
                if ignore_outliner:
                    d = dist_wo_outliers(embeddings[word1], embeddings[word2])
                else:
                    d = torch.dist(embeddings[word1], embeddings[word2]).item()
                dist_matrix[i, j] = d
    sns.heatmap(dist_matrix, xticklabels=words, yticklabels=words, annot=True, cmap='Blues', vmin=0, ax=ax,
                annot_kws={"size": 9})
    ax.set_title(f'Distances between {embeddings_title} Word Embeddings', fontsize=8)

def remove_outliers(data):
    Q1 = np.percentile(data, 25)
    Q3 = np.percentile(data, 75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = ((data < lower_bound) | (data > upper_bound))
    print("outlier_count:", np.sum(outliers.squeeze().numpy()))
    return np.where((data >= lower_bound) & (data <= upper_bound), data, np.nan)


def cossim_wo_outliers(a, b):
    """Use the interquartile range (IQR) method to detect and remove outliers."""
    a_cleaned = remove_outliers(a)
    b_cleaned = remove_outliers(b)
    # Keep only the indices where neither a_cleaned nor b_cleaned is NaN
    valid_indices = ~np.isnan(a_cleaned) & ~np.isnan(b_cleaned)
    a_filtered = a_cleaned[valid_indices]
    b_filtered = b_cleaned[valid_indices]
    if len(a_filtered) == 0 or len(b_filtered) == 0:
        raise ValueError("No valid data points remain after outlier removal.")
    # Compute cosine similarity
    similarity = 1 - cosine(a_filtered, b_filtered)
    return similarity


def dist_wo_outliers(a, b):
    a_cleaned = remove_outliers(a)
    b_cleaned = remove_outliers(b)
    # Keep only the indices where neither a_cleaned nor b_cleaned is NaN
    valid_indices = ~np.isnan(a_cleaned) & ~np.isnan(b_cleaned)
    a_filtered = a_cleaned[valid_indices]
    b_filtered = b_cleaned[valid_indices]
    if len(a_filtered) == 0 or len(b_filtered) == 0:
        raise ValueError("No valid data points remain after outlier removal.")
    # Compute Euclidean distance
    distance = torch.dist(torch.tensor(a_filtered), torch.tensor(b_filtered)).item()
    return distance
